; mon580-2.asm-Include File for Assembler Program
IncHLAndRetIfEqDEWithBrk equ 0FA8DH
IncHLAndRetIfEqDE equ 0FA90H
GET_HL equ 0FAFFH
PrintCRAndHexWordAndSpaceAndCRAndHexWordAndSpace equ 0FB72H
PrintCRAndHexWordBCAndSpace equ 0FB75H
PrintCharFromA equ 0FCA1H
PrintCRAndHexWordAndSpaceAndHexByteMemAndSpace equ 0FDE9H
PrintHexByteFromMemAndSpace equ 0FDECH
PrintHexByteAndSpace equ 0FDEDH
BIOSENTRY equ 0FF70H
FARJZ equ 0FFD3H
FARJMP equ 0FFDCH
BDOS equ 0FFF4H
BDOSRET equ 0FFF9H
; Ende Include File for Assembler Program
