; mon580-2.asm-Include File for Assembler Program
IncHLAndRetIfEqDEWithBrk equ 0FA8DH
IncHLAndRetIfEqDE equ 0FA90H
GET_HL equ 0FAFFH
PrintCharFromA equ 0FCA9H
PrintCRAndHexWordAndSpaceAndHexByteMemAndSpace equ 0FDFCH
PrintHexByteFromMemAndSpace equ 0FDFFH
PrintHexByteAndSpace equ 0FE00H
BIOSENTRY equ 0FF76H
FARJZ equ 0FFD9H
BDOS equ 0FFF4H
BDOSRET equ 0FFF9H
; Ende Include File for Assembler Program
