; mon580-2.asm-Include File for Assembler Program
IncHLAndRetIfEqDEWithBrk equ 0FA7FH
IncHLAndRetIfEqDE equ 0FA82H
GET_HL equ 0FAFFH
PrintCharFromA equ 0FCAAH
PrintCRAndHexWordAndSpaceAndHexByteMemAndSpace equ 0FDFEH
PrintHexByteFromMemAndSpace equ 0FE01H
PrintHexByteAndSpace equ 0FE02H
BIOSENTRY equ 0FF76H
FARJZ equ 0FFD9H
BDOS equ 0FFF4H
BDOSRET equ 0FFF9H
; Ende Include File for Assembler Program
