; อออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ
;  ’๋ คซ๏  คจฎ-86 คซ๏ 580, แฎขฌฅแโจฌ๋ฉ แ เจฎญ-128,
;  ฏฎคคฅเฆชฎฉ VT-52 จ ํฌใซ๏โฎเฎฌ CP/M
; ฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤ
;  ‘จแโฅฌญ๋ฅ ข๋งฎข๋ ’ 
; อออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ

InputSymbol		EQU	0F803H
PrintCharFromC		EQU	0F809H
GetKeyboardStatus	EQU	0F812H
PrintString		EQU	0F818H
PrintHexByte		EQU	0F815H
ReadKeyCode		EQU	0F81BH
InitVideo		EQU	0F82Dh
WarmBoot		EQU	0F86CH
InputDirective		EQU	0F8EEH
Compare_HL_DE		EQU	0F990H
PrintCRAndHexWordAndSpace EQU	0FB78H

