; อออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ
;  ’๋ คซ๏  คจฎ-86 คซ๏ 580, แฎขฌฅแโจฌ๋ฉ แ เจฎญ-128,
;  ฏฎคคฅเฆชฎฉ VT-52 จ ํฌใซ๏โฎเฎฌ CP/M
; ฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤ
;  ‘จแโฅฌญ๋ฅ ข๋งฎข๋ ’ 
; อออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ

InputSymbol			EQU	0F803H
PrintCharFromC		EQU	0F809H
TapeWriteByte		EQU	0F80CH
GetKeyboardStatus	EQU	0F812H
PrintString			EQU	0F818H
PrintHexByte		EQU	0F815H
ReadKeyCode			EQU	0F81BH
CalcChecksum		EQU	0F82AH
InitVideo			EQU	0F82Dh
GetFreeMemAddr		EQU	0F830H
WarmBoot			EQU	0F86CH
InputDirective		EQU	0F8EEH
Compare_HL_DE		EQU	0F990H
PrintCR				EQU	0F9B0H
ReadROM				EQU	0FA68H
PrintCRAndHexWordAndSpace EQU	0FB78H

